# Generated by Django 5.1.7 on 2025-04-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_productcomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر محصول', 'verbose_name_plural': 'نظرات محصول'},
        ),
    ]
