# Generated by Django 5.1.7 on 2025-04-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_alter_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='count',
        ),
    ]
