# Generated by Django 5.1.7 on 2025-04-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_rename_quantity_orderitem_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
