# Generated by Django 5.1.7 on 2025-04-08 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_rename_count_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='کد سفارش سفارش'),
        ),
    ]
