# Generated by Django 5.1.7 on 2025-03-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک های فوتر',
                'verbose_name_plural': 'دسته بندی های لینک فوتر',
            },
        ),
        migrations.CreateModel(
            name='SiteBannerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='عنوان بنر')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس بنر')),
                ('image', models.ImageField(blank=True, max_length=240, null=True, upload_to='images/banners/', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(verbose_name='فعال بودن /غیرفعال بودن')),
                ('start_date', models.DateField(null=True, verbose_name='زمان شروع')),
                ('end_date', models.DateField(null=True, verbose_name='زمان پایان')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزییات محصول'), ('about_us', 'صفحه درباره ما')], max_length=200, verbose_name='جایگاه نمایشی')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='دامنه سایت')),
                ('addres', models.CharField(max_length=500, verbose_name=' آدرس ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن ')),
                ('email', models.EmailField(blank=True, max_length=72, null=True, verbose_name='ایمیل ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo', verbose_name='لوگو سایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت سایت')),
                ('is_main_settings', models.BooleanField(default=False, verbose_name='تنظیمات اصلی سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sliders/', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / فعال نبودن')),
                ('start_date', models.DateField(null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
        migrations.CreateModel(
            name='Takhfif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تخفیف')),
                ('mizan_takhfif', models.CharField(blank=True, max_length=40, null=True, verbose_name='میزان تخفیف')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('description', models.TextField(verbose_name='توضیحات تخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/takhfif', verbose_name='تصویر اسلایدر تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / فعال نبودن')),
                ('start_date', models.DateField(null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'اسلایدر تخفیف',
                'verbose_name_plural': 'اسلایدرهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('footer_link_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_module.footerlinkbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
    ]
