# Generated by Django 5.1.7 on 2025-04-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_options_user_about_user_user_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
