# Generated by Django 5.1.7 on 2025-04-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_user_date_joined_user_email_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='authlog',
            name='event',
            field=models.CharField(choices=[('register', 'ثبت\u200cنام'), ('login', 'ورود'), ('reset', 'بازنشانی رمز')], max_length=20, verbose_name='وضعیت کاربر'),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='success',
            field=models.BooleanField(verbose_name='موفق بودن / نبودن'),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ورود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/users_profile', verbose_name='تصویر کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کارکنان؟ / غیرکارکنان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شماره / تایید نبودن شماره'),
        ),
    ]
